name: Test
on: push
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Check has changes
        id: check-changes
        uses: rdietrick/did-files-change@master
        with:
          pathspec: .

      - name: Debug
        run: |
          echo "Has changes: ${{ steps.check-changes.outputs.changed }}"
